In [ ]:
#import the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1 : Read the Data!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#give path of the source-file and store that path in a variable named census
df = pd.read_csv("/content/drive/MyDrive/makeSenseOfCensus.csv")
df

age  education-num  race  sex  capital-gain  capital-loss  \
0     39             13     4    1          2174             0   
1     50             13     4    1             0             0   
2     38              9     4    1             0             0   
3     53              7     2    1             0             0   
4     28             13     2    0             0             0   
..   ...            ...   ...  ...           ...           ...   
995   56              9     4    1             0             0   
996   45             14     4    1             0             0   
997   48             13     4    1             0             0   
998   40             10     4    1          2580             0   
999   39             13     4    1         15024             0   

     hours-per-week  income  
0                40       0  
1                13       0  
2                40       0  
3                40       0  
4                40       0  
..              ...     ...  
995              55       1  
996              45       0  
997              58       1  
998              40       0  
999              50       1  

[1000 rows x 8 columns]

In [ ]:
df.head()

age  education-num  race  sex  capital-gain  capital-loss  hours-per-week  \
0   39             13     4    1          2174             0              40   
1   50             13     4    1             0             0              13   
2   38              9     4    1             0             0              40   
3   53              7     2    1             0             0              40   
4   28             13     2    0             0             0              40   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
df.tail()

age  education-num  race  sex  capital-gain  capital-loss  \
995   56              9     4    1             0             0   
996   45             14     4    1             0             0   
997   48             13     4    1             0             0   
998   40             10     4    1          2580             0   
999   39             13     4    1         15024             0   

     hours-per-week  income  
995              55       1  
996              45       0  
997              58       1  
998              40       0  
999              50       1

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.describe()

age  education-num         race          sex  capital-gain  \
count  1000.00000    1000.000000  1000.000000  1000.000000   1000.000000   
mean     38.05100      10.084000     3.653000     0.671000    588.526000   
std      13.34948       2.548615     0.854003     0.470085   2618.537515   
min      17.00000       1.000000     0.000000     0.000000      0.000000   
25%      28.00000       9.000000     4.000000     0.000000      0.000000   
50%      36.00000      10.000000     4.000000     1.000000      0.000000   
75%      46.00000      12.000000     4.000000     1.000000      0.000000   
max      90.00000      16.000000     4.000000     1.000000  34095.000000   

       capital-loss  hours-per-week      income  
count   1000.000000     1000.000000  1000.00000  
mean      92.960000       39.876000     0.23200  
std      412.442337       12.018114     0.42232  
min        0.000000        1.000000     0.00000  
25%        0.000000       40.000000     0.00000  
50%        0.000000       40.000000     0.00000  
75%        0.000000       45.000000     0.00000  
max     2415.000000       99.000000     1.00000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             1000 non-null   int64
 1   education-num   1000 non-null   int64
 2   race            1000 non-null   int64
 3   sex             1000 non-null   int64
 4   capital-gain    1000 non-null   int64
 5   capital-loss    1000 non-null   int64
 6   hours-per-week  1000 non-null   int64
 7   income          1000 non-null   int64
dtypes: int64(8)
memory usage: 62.6 KB


##Data Analysis

In [ ]:
# Perform basic statistical analyses such as finding maximum, minimum, mean, and standard deviation
# finding maximum, minimum, mean, and standard deviation
print(df.max())

age                  90
education-num        16
race                  4
sex                   1
capital-gain      34095
capital-loss       2415
hours-per-week       99
income                1
dtype: int64


In [ ]:
print(df.min())

age               17
education-num      1
race               0
sex                0
capital-gain       0
capital-loss       0
hours-per-week     1
income             0
dtype: int64


In [ ]:
print(df.mean())

age                38.051
education-num      10.084
race                3.653
sex                 0.671
capital-gain      588.526
capital-loss       92.960
hours-per-week     39.876
income              0.232
dtype: float64


In [ ]:
print(df.std())

age                 13.349480
education-num        2.548615
race                 0.854003
sex                  0.470085
capital-gain      2618.537515
capital-loss       412.442337
hours-per-week      12.018114
income               0.422320
dtype: float64


# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [ ]:
data = np.genfromtxt('/content/drive/MyDrive/makeSenseOfCensus.csv', delimiter=',', skip_header=1)
print("\nData:\n\n", data)


Data:

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [ ]:
#print the type of data
print(type(data))

<class 'numpy.ndarray'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [ ]:
new_record = [[50,9,4,1,0,0,40,0]]
# using np.concatenate()
new_record = np.array(new_record)
data = np.concatenate((data,new_record))
print(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [ ]:
new_record = [[50,9,4,1,0,0,40,0]]
new_record = np.array(new_record)
data = np.concatenate((data,new_record))
print(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [50.  9.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


In [ ]:
#display after appending the new record at the end of the array.
print(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [50.  9.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [ ]:
# Check if it's a young country or old country
age = data[:,0]
print(age)

[39. 50. 38. ... 50. 50. 50.]


Find the max age and store it in a variable called 'max_age'.



In [ ]:
#print the max_age
max_age = np.max(age)
print(max_age)

90.0


Find the min age and store it in a variable called 'min_age'.

In [ ]:
#print the min_age
min_age = np.min(age)
print(min_age)

17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [ ]:
#print the age_mean
age_mean = np.mean(age)
print(age_mean)

38.09860557768924


Find the standard deviation of the age and store it in a variable called 'age_std'

In [ ]:
#print the age_std
age_std = np.std(age)
print(age_std)

13.33745430352488


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [ ]:
arr = data[:,2]
race_0 = data[arr==0]
race_1 = data[arr==1]
race_2 = data[arr==2]
race_3 = data[arr==3]
race_4 = data[arr==4]
print(race_0)

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]


Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [ ]:
#len_0
len_0 = len(race_0)
print(len_0)

10


In [ ]:
#len_1
len_1 = len(race_1)
print(len_1)

27


In [ ]:
#len_2
len_2 = len(race_2)
print(len_2)

110


In [ ]:
#len_3
len_3 = len(race_3)
print(len_3)

6


In [ ]:
#len_4
len_4 = len(race_4)
print(len_4)

851


Find out which is the race with the maximum no. of citizens

---



In [ ]:
# Find out which is the race with the maximum no. of citizens
print(max(len_0,len_1,len_2,len_3,len_4))

851


Find out which is the race with the minimum no. of citizens

In [ ]:
# Find out which is the race with the minimum no. of citizens
# minimum no. of citizens
print(min(len_0,len_1,len_2,len_3,len_4))

6


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
minority_race = np.argmax([len_0,len_1,len_2,len_3,len_4])
print(minority_race)


4


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
minority_race = np.argmin([len_0,len_1,len_2,len_3,len_4])
print(minority_race)

3


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [ ]:
#from age column, filter out age data > 60
senior_citizens = data[data[:, 0] > 60]
print(senior_citizens)

[[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e+00 2.2060e+03
  

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [ ]:
senior_citizens = data[data[:, 0] > 60]
working_hours_sum = senior_citizens[:, 6].sum()
print(f"Total working hours for senior citizens: {working_hours_sum}")

Total working hours for senior citizens: 1917.0


c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [ ]:
senior_citizens_len = len(senior_citizens)
print(f"Number of senior citizens: {senior_citizens_len}")

Number of senior citizens: 61


d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [ ]:
avg_working_hours = working_hours_sum / senior_citizens_len
print(f"Average working hours of senior citizens: {avg_working_hours}")


Average working hours of senior citizens: 31.42622950819672


e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [ ]:
# Print the average working hours
print(f"Average working hours of senior citizens: {avg_working_hours}")

# Check if the government's policy is followed
if avg_working_hours <= 25:
    print("The government policy is followed.")
else:
    print("The government policy is not followed.")

Average working hours of senior citizens: 31.42622950819672
The government policy is not followed.


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [ ]:
census = np.genfromtxt('/content/drive/MyDrive/makeSenseOfCensus.csv', delimiter=',')
high = census[census[:, 1] > 10]
low = census[census[:, 1] <= 10]

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [ ]:
avg_pay_high = np.mean(high[:, 7])
print(f"Average Pay for Higher Educated People: {avg_pay_high:.2f}")

Average Pay for Higher Educated People: 0.43


In [ ]:
avg_pay_low = np.mean(low[:, 7])
print(f"Average Pay for Lower Educated People: {avg_pay_low:.2f}")

Average Pay for Lower Educated People: 0.14
